### ISSUE TITLE
Error loading in Fragment

### ISSUE THREAD

**Issue by varunagarwal315** [timehop/sticky-headers-recyclerview#65] opened 2015-08-16 14:42 UTC
I have used this code successfully from my Main Activity in which I am loading data from my server onto the cards used in recycerview. Everything is working fine but now when I tried to shift the exact same code onto a fragment, it keeps giving me an error. I have changed all the getActivity to view.getContext() and made other appropriate changes in the import. Could someone help me out?
```
 Process: varun.brandlabs.com.zeko, PID: 13859
    android.view.InflateException: Binary XML file line #8: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:633)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at varun.brandlabs.com.zeko.NewsFeed.MyStickyAdapter.onCreateHeaderViewHolder(MyStickyAdapter.java:53)
            at varun.brandlabs.com.zeko.NewsFeed.MyStickyAdapter.onCreateHeaderViewHolder(MyStickyAdapter.java:22)
            at com.timehop.stickyheadersrecyclerview.caching.HeaderViewCache.getHeader(HeaderViewCache.java:34)
            at com.timehop.stickyheadersrecyclerview.StickyRecyclerHeadersDecoration.getHeaderView(StickyRecyclerHeadersDecoration.java:138)
            at com.timehop.stickyheadersrecyclerview.StickyRecyclerHeadersDecoration.getItemOffsets(StickyRecyclerHeadersDecoration.java:64)
            at android.support.v7.widget.RecyclerView.getItemDecorInsetsForChild(RecyclerView.java:3583)
            at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:6623)
            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1385)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1322)
            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:556)
            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2673)
            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2971)
            at android.view.View.layout(View.java:15631)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:562)
            at android.view.View.layout(View.java:15631)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
            at android.view.View.layout(View.java:15631)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1626)
            at android.view.View.layout(View.java:15631)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
            at android.view.View.layout(View.java:15631)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15631)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
            at android.view.View.layout(View.java:15631)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15631)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
            at android.view.View.layout(View.java:15631)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15631)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2101)
            at android.view.ViewRootImpl.performTraversals(View


public class MyStickyAdapter extends RecyclerView.Adapter<MyStickyAdapter.ViewHolder>
        implements StickyRecyclerHeadersAdapter<RecyclerView.ViewHolder> {
    Context mContext;

    MyStickyAdapter(Context mContext){this.mContext=mContext;}

    public static class ViewHolder extends RecyclerView.ViewHolder{
        public TextView HeadView, Row;
        public CardView cardView; ImageView image;

        ViewHolder(final View view){
            super(view);

        }
    }

    @Override
    public long getHeaderId(int position) {
            return position;
    }

    @Override
    public ViewHolder onCreateViewHolder(ViewGroup viewGroup, int i) {
        View v = LayoutInflater.from(viewGroup.getContext())
                .inflate(R.layout.sample_feed_card, viewGroup, false);
        ViewHolder viewHolder = new ViewHolder(v);
        return viewHolder;
    }

    @Override
    public ViewHolder onCreateHeaderViewHolder(ViewGroup parent) {
        View v = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.sample_feed_header, parent, false);
        ViewHolder viewHolder=new ViewHolder(v);
        return viewHolder;
    }

    @Override
    public void onBindHeaderViewHolder(RecyclerView.ViewHolder holder, int position) {

    }

    @Override
    public void onBindViewHolder (ViewHolder holder, int i) {

    }

    @Override
    public int getItemCount() {
       return 4;
    }
    @Override
    public void onAttachedToRecyclerView(RecyclerView recyclerView) {
        super.onAttachedToRecyclerView(recyclerView);
    }

}
```

As of now the code above is using default values iv placed so the childs all look the same.
2) I keep loading data asynchronously, so i need to mAdapter.add(newData) and then mAdapter.notifyItemRangeChanged. Does that work efficiently with this?

**Comment by jacobtabak** [comment] 2015-08-17 04:04
Your stack trace is truncated due to the 4000 character limit of logcat so I can't tell you exactly what the problem is.  This is a pretty common problem when exceptions happen during layout.  I would suggest temporarily wrapping line 53 of MyStickyAdapter.java with a try/catch block.  This is probably layout inflater code.  Then, put a breakpoint in the exception handler and you can take a look at the cause of the exception.

**Comment by varunagarwal315** [comment] 2015-08-17 04:27
I was using a custom circular image view library in my header row. Line53
was inflation of the header row. Once I removed the image View, it started
to work. I guess I will have to look at the library but for now the code is
working well. Thanks a lot.

I had another question if you dont mind. I am downloading data from my
Parse Server, saving it in a ArrayList, and updating recycler View with it.
Say user does pull to refresh, and new items are inserted in the array List
then in normal recyclerview I would use mAdapter.notifyDataSetChanged or
DataRangeInserted. It is mentioned that

The StickyHeaders aren't aware of your adapter so if you must notify them
when your data set changes.

    mAdapter.registerAdapterDataObserver(new
RecyclerView.AdapterDataObserver() {
      @Override public void onChanged() {
        headersDecor.invalidateHeaders();
      }
    });

So where do I call this function? Below code is done on main fragment.
mAdapter.add(mList)  // at this point it is null and data is added after
every pull.
ParseQuery query= ParseQuery.getQuery("name")
query.findInBackground . . . .
 . . . . .
mList.add(product);
mAdapter.notifyItemRangeInserted(Int x, Int y);


Thanks,
Varun Agarwal

**Comment by jacobtabak** [comment] 2015-08-17 14:13
You would call that method just once immediately after instantiating the adapter.  Like in `onCreate` for example,

adapter = new MyStickyAdapter();
adapter.registerAdapterDataObserver(...)

**Comment by erumhannan** [comment] 2015-08-22 09:29
varunagarwal315   can u share how u resolve issue of data adding in gridview onScroll Listener same as just we do load data onScroll in listview http://www.dailymotion.com/dm_5233001e62925 pls see this how to achieve this same scenerio in gridview

**Comment by varunagarwal315** [comment] 2015-08-22 10:24
I didn't understand you question.  Im using this recyclerview library.  Do
you mean how to add more days when user scrolls to the bottom of the list?
Or how I used Picasso? I'm currently out of town so I don't have my
laptop.  Should get back home tomorrow.

**Comment by erumhannan** [comment] 2015-08-23 12:37
ok i m posting question here @varunagarwal315  my requirement is actually i need footer or button at the end of every section that will be named as  "VIEW MORE"  once user click on that button then it will behave same as we load data in onScroll of listview it will add more 10 items from server in thas section  at the end of every section i need  "VIEW MORE" button i have only 2 sections ? how will i do ?

**Comment by jacobtabak** [comment] 2015-08-23 19:26
Please do not hijack other issues trying to get support for your issue.  StackOverflow, reddit, etc are all better places for these types of questions.  If there's an unresolved issue here @varunagarwal315 please open up a new one, closing this for now.

**Closed by jacobtabak** 2015-08-23 19:26 UTC

**Comment by varunagarwal315** [comment] 2016-09-01 11:49
Hey timehop/sticky-heade,

Discover high quality jobs and connect with recruiters on LinkedIn.

- Varun

Accept invite: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=ITzmYnhy&invitationId=6177079454788050944&trk=eml-invite_guest-invite_guest-101-india_a&trkEmail=eml-invite_guest-invite_guest-101-india_a-null-0%7Eisk9qfa4%7E4d

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-isk9qfa4-4d&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQH83rO4jWpjfAAAAVbllKOq1i0YMq40IioR8xQC7u4rPSRd3IButrzAGB8pJtmWilbPNlmP1sWZ9bkrvK6diyzRSZ7HC5I3thd2_DSVV89tInjuBAylPAuZCbv1eecd7S7L76Ufbz57S9K7ArIsWDh2A2gP89Ix_1H-yGYlL0s-ujNuFlaeGGOyM32_SCyWYP6i&eid=0-isk9qfa4-4d

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-isk9qfa4-4d&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by varunagarwal315** [comment] 2016-09-01 11:49
Hey timehop/sticky-heade,

Discover high quality jobs and connect with recruiters on LinkedIn.

- Varun

Accept invite: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=8FsWyFYp&invitationId=6177079450753122305&trk=eml-invite_guest-invite_guest-101-india_a&trkEmail=eml-invite_guest-invite_guest-101-india_a-null-0%7Eisk9rcwq%7Edn

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-isk9rcwq-dn&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEgcEdBcb3tKgAAAVbllT5kz8Iu3d4PZoK1lNCv_2kLQEh6FAEAce3wJmtBEg-ILpZ5IlTbr8mtVLdXYCb_foVAkhYzK-BCrinPnbJpk6xQNmuzNDA8OjUDaDMpCv0-8o9t8R8dpWeDlH1ybiNfu7eZx5oTc5PyDpcfzE4mknVBRKw42tgmJ3tDsdafl_mZrDLy&eid=0-isk9rcwq-dn

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-isk9rcwq-dn&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by varunagarwal315** [comment] 2016-09-07 07:08
Varun Agarwal would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=8FsWyFYp&invitationId=6177079450753122305&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-atcmf7%7Eissezf0p%7Eav

View Varun Agarwal&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=8FsWyFYp&invitationId=6177079450753122305&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-atcmf7%7Eissezf0p%7Eav

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=atcmf7-issezf0p-av&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=atcmf7-issezf0p-av&loid=AQEb9R-2XmvW5QAAAVcDeWfi_FvwrEpCFc0yBFmGpXG8v-IDpSyPLuNrKAT5iplBoJ9HTfoAjsgYPby8liqR1LoXcNag3y-aZWKU-Zz9o6tiwDmaS428owAa80FdajUMmp0BUm13RhnrS1szabTvSBv0sGDV2l0Bo1GFj2bxxWITgP_oQ0El0NErEpycpx-pMD6M

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=atcmf7-issezf0p-av&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by varunagarwal315** [comment] 2016-09-07 07:08
Varun Agarwal would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-h60hwz-issez9il-hh&t=ssuw&ek=first_guest_reminder_01&li=121&m=hero&ts=accept_text&sharedKey=ITzmYnhy&invitationId=6177079454788050944

View Varun Agarwal&#39;s profile: https://www.linkedin.com/e/v2?e=-h60hwz-issez9il-hh&t=ssuw&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=ITzmYnhy&invitationId=6177079454788050944

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-h60hwz-issez9il-hh&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-h60hwz-issez9il-hh&loid=AQG4RUbUpKtNwwAAAVcDedm_rF3T_lTFDnVghUnQoG3pC1nCRqeLTCrPJzj0g32ONtJdLGs397y00YorZN59wl6Lnanf8zkBZwJA4icNegxnmEhw2trcrfCHQhFUl8Q-e-oXkQ_4irQQZ_a-OVpos_lEBx2gATdGg_NXndoA6pju7xkPG8MmjmPjejGtppGGzSDh

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-h60hwz-issez9il-hh&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by varunagarwal315** [comment] 2016-09-14 07:17
Hi ,

Varun Agarwal would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=ITzmYnhy&invitationId=6177079454788050944&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-%7Eh60hwz%7Eit2eelga%7E8

View Varun Agarwal&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=ITzmYnhy&invitationId=6177079454788050944&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-%7Eh60hwz%7Eit2eelga%7E8

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-h60hwz-it2eelga-8&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=-h60hwz-it2eelga-8&loid=AQFGlWFJQpO3LwAAAVcnjo1bACZH15BZJeUBrlz3uf5lw79F9EpTq5rKv80-4dSgrxSVE2G4lcHk1IekBsKZFED_sRwwWROVIP8ens_3KtPI6zANCr6E5LH2ZnGWMqz7llKbAQpu2hKN5EMV6oEd_P1WUwxIzVTEHkSKBac_zS3GsDrQHkbL5eu3Hd56lmjxaLg-

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-h60hwz-it2eelga-8&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by varunagarwal315** [comment] 2016-09-14 07:21
Hi ,

Varun Agarwal would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=8FsWyFYp&invitationId=6177079450753122305&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-atcmf7%7Eit2eelga%7El7

View Varun Agarwal&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=8FsWyFYp&invitationId=6177079450753122305&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-atcmf7%7Eit2eelga%7El7

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=atcmf7-it2eelga-l7&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=atcmf7-it2eelga-l7&loid=AQEO67bfH9UzQwAAAVcnkmR6PeMg60_1XtQb9_dQhoVfhX3UxkapaW5dvdfr1D_Krnu3sttPKjMfuHqGc6uf5suxO7CnZ0GNgpqlFSleA9dSJQ1-C2VoKBeGL_a80FVaGJKh-ftGBKnyOJg4ZCJaSjl8nyvgYVKICtRlDvtfHk5uYjzToJoXRyo5uPS1fMM15pSG

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=atcmf7-it2eelga-l7&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
